export const projects = [
  {
    title: 'HITPLAY',
    description: "Hitplay is an app that allows users to vote between two tracks from Spotify's 'Top 100 Most Streamed' playlist. It also allows users to listen to a preview of each track.",
    image: '/images/hitplaymockup.png',
    tags: ['Next JS', 'Prisma', 'Tailwind CSS'],
    source: 'https://hitplay.vercel.app',
    visit: 'https://hitplay.vercel.app',
    id: 0,
  },
  {
    title: 'SOLO SHOP',
    description: 'Solo Shop is an ecommerce shop for selling hoodies. It was built with NextJS and Tailwind CSS for styling. The website will go live soon and make transactions using Stripe.',
    image: '/images/hoodieShopMockup.png',
    tags: ['Next JS', 'Sanity', 'Stripe'],
    source: 'https://soloshop.vercel.app',
    visit: 'https://soloshop.vercel.app',
    id: 1,
  },
  
  {
    title: 'KRYPT',
    description: 'Krypt is a website connected to the blockchain capable of making real transactions on the ethereum network. The transaction is made possible with the help of MetaMask and HardHat',
    image: '/images/kryptWallet-mockup.png',
    tags: ['React', 'Solidity'],
    source: 'https://kryptowallet.netlify.app/',
    visit: 'https://kryptowallet.netlify.app/',
    id: 2,
  },
  {
    title: 'SHARE ME',
    description:"Share Me is a social media website similar to Pinterest. After signing in with google, the user is able to post their favorite pictures, or browse using specific categories.",
    image: '/images/soloshareme-mockup.png',
    tags: ['React', 'Sanity'],
    source: 'https://soloshareme.netlify.app',
    visit: 'https://soloshareme.netlify.app',
    id: 3,
  },
  {
    title: 'Work 2 Play Rentals',
    description: "Work 2 Play is a jetski rental site built for a business located in Clinton, UT. This site is built with NextJS and Tailwind CSS for styling.",
    image: '/images/work2play-mockup.png',
    tags: ['Next JS', 'Tailwind CSS', 'Sanity'],
    source: 'https://work2playutah.com',
    visit: 'https://work2playutah.com',
    id: 4,
  },
];
